const API_BASE_URL = '';

export const API_ENDPOINTS = {
  auth: {
    login: `${API_BASE_URL}/api/v1/auth/login`,
    logout: `${API_BASE_URL}/api/v1/auth/logout`,
    me: `${API_BASE_URL}/api/v1/auth/me`,
  },
  users: {
    getAll: `${API_BASE_URL}/api/v1/users`,
    getOne: (id: string) => `${API_BASE_URL}/api/v1/users/${id}`,
    create: `${API_BASE_URL}/api/v1/users`,
    update: (id: string) => `${API_BASE_URL}/api/v1/users/${id}`,
    delete: (id: string) => `${API_BASE_URL}/api/v1/users/${id}`,
    changePassword: (id: string) => `${API_BASE_URL}/api/v1/users/${id}/password`,
  },
  apiKeys: {
    base: `${API_BASE_URL}/api/v1/api-keys`,
    get: `${API_BASE_URL}/api/v1/api-keys`,
    update: `${API_BASE_URL}/api/v1/api-keys`,
    delete: (provider: string) => `${API_BASE_URL}/api/v1/api-keys/${provider}`,
  },
  pdfTemplate: {
    get: `${API_BASE_URL}/api/v1/pdf-template`,
    update: `${API_BASE_URL}/api/v1/pdf-template`,
  },
  uploadedFiles: {
    getAll: `${API_BASE_URL}/api/v1/uploaded-files`,
    upload: `${API_BASE_URL}/api/v1/uploaded-files/upload`,
    delete: (id: number) => `${API_BASE_URL}/api/v1/uploaded-files/${id}`,
    download: (id: number) => `${API_BASE_URL}/api/v1/uploaded-files/download/${id}`,
    publicCompanyLogo: `${API_BASE_URL}/api/v1/uploaded-files/public/company-logo`,
    masterStocks: (query: string) => `${API_BASE_URL}/api/v1/uploaded-files/master-stocks?q=${encodeURIComponent(query)}`,
  },
  channels: {
    getAll: `${API_BASE_URL}/api/v1/channels`,
    create: `${API_BASE_URL}/api/v1/channels`,
    update: (id: number) => `${API_BASE_URL}/api/v1/channels/${id}`,
    delete: (id: number) => `${API_BASE_URL}/api/v1/channels/${id}`,
  },
  mediaRationale: {
    fetchVideo: `${API_BASE_URL}/api/v1/media-rationale/fetch-video`,
    startAnalysis: `${API_BASE_URL}/api/v1/media-rationale/start-analysis`,
    getJob: (jobId: string) => `${API_BASE_URL}/api/v1/media-rationale/job/${jobId}`,
    restartStep: (jobId: string, stepNumber: number) => `${API_BASE_URL}/api/v1/media-rationale/restart-step/${jobId}/${stepNumber}`,
    getCsv: (jobId: string) => `${API_BASE_URL}/api/v1/media-rationale/job/${jobId}/csv`,
    updateCsv: (jobId: string) => `${API_BASE_URL}/api/v1/media-rationale/job/${jobId}/csv`,
    generatePdf: (jobId: string) => `${API_BASE_URL}/api/v1/media-rationale/job/${jobId}/generate-pdf`,
    save: (jobId: string) => `${API_BASE_URL}/api/v1/saved-rationale/save`,
    uploadSigned: (jobId: string) => `${API_BASE_URL}/api/v1/saved-rationale/upload-signed`,
    downloadPdf: (filePath: string) => `${API_BASE_URL}/api/v1/saved-rationale/download/${encodeURIComponent(filePath)}`,
    deleteJob: (jobId: string) => `${API_BASE_URL}/api/v1/media-rationale/job/${jobId}`,
    csvPreview: (jobId: string) => `${API_BASE_URL}/api/v1/media-rationale/job/${jobId}/csv-preview`,
    downloadCsv: (jobId: string) => `${API_BASE_URL}/api/v1/media-rationale/job/${jobId}/download-csv`,
    uploadCsv: (jobId: string) => `${API_BASE_URL}/api/v1/media-rationale/job/${jobId}/upload-csv`,
    continuePipeline: (jobId: string) => `${API_BASE_URL}/api/v1/media-rationale/job/${jobId}/continue-pipeline`,
    step8CsvPreview: (jobId: string) => `${API_BASE_URL}/api/v1/media-rationale/job/${jobId}/step8-csv-preview`,
    step8DownloadCsv: (jobId: string) => `${API_BASE_URL}/api/v1/media-rationale/job/${jobId}/step8-download-csv`,
    step8UploadCsv: (jobId: string) => `${API_BASE_URL}/api/v1/media-rationale/job/${jobId}/step8-upload-csv`,
    step8ContinuePipeline: (jobId: string) => `${API_BASE_URL}/api/v1/media-rationale/job/${jobId}/step8-continue-pipeline`,
  },
  premiumRationale: {
    createJob: `${API_BASE_URL}/api/v1/premium-rationale/create-job`,
    getJob: (jobId: string) => `${API_BASE_URL}/api/v1/premium-rationale/jobs/${jobId}`,
    downloadCsv: (jobId: string) => `${API_BASE_URL}/api/v1/premium-rationale/jobs/${jobId}/csv`,
    uploadCsv: (jobId: string) => `${API_BASE_URL}/api/v1/premium-rationale/jobs/${jobId}/upload-csv`,
    continueToPdf: (jobId: string) => `${API_BASE_URL}/api/v1/premium-rationale/jobs/${jobId}/continue-to-pdf`,
    save: (jobId: string) => `${API_BASE_URL}/api/v1/premium-rationale/job/${jobId}/save`,
    uploadSigned: (jobId: string) => `${API_BASE_URL}/api/v1/saved-rationale/upload-signed`,
    downloadPdf: (filePath: string) => `${API_BASE_URL}/api/v1/saved-rationale/download/${encodeURIComponent(filePath)}`,
    deleteJob: (jobId: string) => `${API_BASE_URL}/api/v1/premium-rationale/jobs/${jobId}`,
    restartStep: (jobId: string, stepNumber: number) => `${API_BASE_URL}/api/v1/premium-rationale/restart-step/${jobId}/${stepNumber}`,
  },
  manualRationale: {
    createJob: `${API_BASE_URL}/api/v1/manual-rationale/create-job`,
    getJob: (jobId: string) => `${API_BASE_URL}/api/v1/manual-rationale/jobs/${jobId}`,
    save: (jobId: string) => `${API_BASE_URL}/api/v1/manual-rationale/job/${jobId}/save`,
    uploadSigned: (jobId: string) => `${API_BASE_URL}/api/v1/saved-rationale/upload-signed`,
    downloadPdf: (filePath: string) => `${API_BASE_URL}/api/v1/saved-rationale/download/${encodeURIComponent(filePath)}`,
    deleteJob: (jobId: string) => `${API_BASE_URL}/api/v1/manual-rationale/jobs/${jobId}`,
    restartStep: (jobId: string, stepNumber: number) => `${API_BASE_URL}/api/v1/manual-rationale/restart-step/${jobId}/${stepNumber}`,
  },
  manualV2: {
    stocks: (query: string) => `${API_BASE_URL}/api/v1/manual-v2/stocks?q=${encodeURIComponent(query)}`,
    createJob: `${API_BASE_URL}/api/v1/manual-v2/jobs`,
    getJob: (jobId: string) => `${API_BASE_URL}/api/v1/manual-v2/jobs/${jobId}`,
    runPipeline: (jobId: string) => `${API_BASE_URL}/api/v1/manual-v2/jobs/${jobId}/run`,
    getSteps: (jobId: string) => `${API_BASE_URL}/api/v1/manual-v2/jobs/${jobId}/steps`,
    save: (jobId: string) => `${API_BASE_URL}/api/v1/manual-v2/jobs/${jobId}/save`,
    uploadSigned: (jobId: string) => `${API_BASE_URL}/api/v1/manual-v2/jobs/${jobId}/upload-signed`,
    downloadPdf: (jobId: string) => `${API_BASE_URL}/api/v1/manual-v2/jobs/${jobId}/download`,
  },
  bulkRationale: {
    base: `${API_BASE_URL}/api/v1/bulk-rationale`,
    createJob: `${API_BASE_URL}/api/v1/bulk-rationale/create-job`,
    getJob: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}`,
    deleteJob: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}`,
    save: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}/save`,
    uploadSigned: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}/upload-signed`,
    downloadPdf: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}/download`,
    restartStep: (jobId: string, stepNumber: number) => `${API_BASE_URL}/api/v1/bulk-rationale/restart-step/${jobId}/${stepNumber}`,
    editInput: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}/edit-input`,
    step4CsvPreview: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}/step4-csv-preview`,
    step4DownloadCsv: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}/step4-download-csv`,
    step4UploadCsv: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}/step4-upload-csv`,
    step4ContinuePipeline: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}/step4-continue-pipeline`,
    step4SaveEdits: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}/step4-save-edits`,
    scripMasterLookup: (symbol: string, exchange?: string) =>
      `${API_BASE_URL}/api/v1/bulk-rationale/scrip-master/lookup?symbol=${encodeURIComponent(symbol)}${exchange ? `&exchange=${encodeURIComponent(exchange)}` : ''}`,
    failedCharts: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}/failed-charts`,
    uploadChart: (jobId: string, stockIndex: number) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}/upload-chart/${stockIndex}`,
    step6ContinuePipeline: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}/step6-continue-pipeline`,
    skipFailedCharts: (jobId: string) => `${API_BASE_URL}/api/v1/bulk-rationale/jobs/${jobId}/skip-failed-charts`,
  },
  savedRationale: {
    getAll: `${API_BASE_URL}/api/v1/saved-rationale`,
    getOne: (id: number) => `${API_BASE_URL}/api/v1/saved-rationale/${id}`,
    save: `${API_BASE_URL}/api/v1/saved-rationale/save`,
    uploadSigned: `${API_BASE_URL}/api/v1/saved-rationale/upload-signed`,
    downloadPdf: (filePath: string) => `${API_BASE_URL}/api/v1/saved-rationale/download/${encodeURIComponent(filePath)}`,
  },
  activityLogs: {
    getAll: `${API_BASE_URL}/api/v1/activity-logs`,
    create: `${API_BASE_URL}/api/v1/activity-logs`,
  },
  generateChart: {
    stocks: (query: string) => `${API_BASE_URL}/api/v1/generate-chart/stocks?q=${encodeURIComponent(query)}`,
    stockDetails: (symbol: string) => `${API_BASE_URL}/api/v1/generate-chart/stock-details?symbol=${encodeURIComponent(symbol)}`,
    generate: `${API_BASE_URL}/api/v1/generate-chart/generate`,
    view: (chartId: string) => `${API_BASE_URL}/api/v1/generate-chart/view/${chartId}`,
    download: (chartId: string) => `${API_BASE_URL}/api/v1/generate-chart/download/${chartId}`,
  },
  aiTranscribe: {
    list: `${API_BASE_URL}/api/v1/ai-transcribe/list`,
    createJob: `${API_BASE_URL}/api/v1/ai-transcribe/create-job`,
    getJob: (jobId: string) => `${API_BASE_URL}/api/v1/ai-transcribe/jobs/${jobId}`,
    deleteJob: (jobId: string) => `${API_BASE_URL}/api/v1/ai-transcribe/jobs/${jobId}`,
    downloadTranscript: (jobId: string) => `${API_BASE_URL}/api/v1/ai-transcribe/jobs/${jobId}/transcript`,
    fetchMetadata: `${API_BASE_URL}/api/v1/ai-transcribe/fetch-metadata`,
    saveTranscriptAndTranslate: (jobId: string) => `${API_BASE_URL}/api/v1/ai-transcribe/jobs/${jobId}/save-transcript-and-translate`,
    saveTranslationAndExtract: (jobId: string) => `${API_BASE_URL}/api/v1/ai-transcribe/jobs/${jobId}/save-translation-and-extract`,
    saveExtracted: (jobId: string) => `${API_BASE_URL}/api/v1/ai-transcribe/jobs/${jobId}/save-extracted`,
    sendToBulk: (jobId: string) => `${API_BASE_URL}/api/v1/ai-transcribe/jobs/${jobId}/send-to-bulk`,
    restartStep: (jobId: string, stepNumber: number) => `${API_BASE_URL}/api/v1/ai-transcribe/jobs/${jobId}/restart-step/${stepNumber}`,
  },
  voiceTyping: {
    list: `${API_BASE_URL}/api/v1/voice-typing/jobs`,
    create: `${API_BASE_URL}/api/v1/voice-typing/jobs`,
    get: (jobId: string) => `${API_BASE_URL}/api/v1/voice-typing/jobs/${jobId}`,
    update: (jobId: string) => `${API_BASE_URL}/api/v1/voice-typing/jobs/${jobId}`,
    delete: (jobId: string) => `${API_BASE_URL}/api/v1/voice-typing/jobs/${jobId}`,
    translate: (jobId: string) => `${API_BASE_URL}/api/v1/voice-typing/jobs/${jobId}/translate`,
    arrange: (jobId: string) => `${API_BASE_URL}/api/v1/voice-typing/jobs/${jobId}/arrange`,
    sendToBulk: (jobId: string) => `${API_BASE_URL}/api/v1/voice-typing/jobs/${jobId}/send-to-bulk`,
    createFromUpload: `${API_BASE_URL}/api/v1/voice-typing/jobs/upload`,
    cancel: (jobId: string) => `${API_BASE_URL}/api/v1/voice-typing/jobs/${jobId}`,
    uploadAudio: (jobId: string) => `${API_BASE_URL}/api/v1/voice-typing/jobs/${jobId}/upload-audio`,
  },
  assistant: {
    chat: `${API_BASE_URL}/api/v1/assistant/chat`,
    activeJobs: `${API_BASE_URL}/api/v1/assistant/active-jobs`,
    diagnose: (jobId: string) => `${API_BASE_URL}/api/v1/assistant/job/${jobId}/diagnose`,
  },
  liveTranscribe: {
    list: `${API_BASE_URL}/api/v1/live-transcribe/jobs`,
    create: `${API_BASE_URL}/api/v1/live-transcribe/jobs`,
    get: (jobId: string) => `${API_BASE_URL}/api/v1/live-transcribe/jobs/${jobId}`,
    update: (jobId: string) => `${API_BASE_URL}/api/v1/live-transcribe/jobs/${jobId}`,
    delete: (jobId: string) => `${API_BASE_URL}/api/v1/live-transcribe/jobs/${jobId}`,
    stop: (jobId: string) => `${API_BASE_URL}/api/v1/live-transcribe/jobs/${jobId}/stop`,
    extract: (jobId: string) => `${API_BASE_URL}/api/v1/live-transcribe/jobs/${jobId}/extract`,
    sendToBulk: (jobId: string) => `${API_BASE_URL}/api/v1/live-transcribe/jobs/${jobId}/send-to-bulk`,
    fetchMetadata: `${API_BASE_URL}/api/v1/live-transcribe/fetch-metadata`,
  },
  mediaPresence: {
    list: `${API_BASE_URL}/api/v1/media-presence`,
    create: `${API_BASE_URL}/api/v1/media-presence`,
    get: (id: number) => `${API_BASE_URL}/api/v1/media-presence/${id}`,
    update: (id: number) => `${API_BASE_URL}/api/v1/media-presence/${id}`,
    delete: (id: number) => `${API_BASE_URL}/api/v1/media-presence/${id}`,
    saveTranscript: (id: number) => `${API_BASE_URL}/api/v1/media-presence/${id}/save-transcript`,
    startVoiceTyping: (id: number) => `${API_BASE_URL}/api/v1/media-presence/${id}/start-voice-typing`,
    startLiveTranscribe: (id: number) => `${API_BASE_URL}/api/v1/media-presence/${id}/start-live-transcribe`,
    startAiTranscribe: (id: number) => `${API_BASE_URL}/api/v1/media-presence/${id}/start-ai-transcribe`,
    startAuto: (id: number) => `${API_BASE_URL}/api/v1/media-presence/${id}/start-auto`,
    syncStatus: (id: number) => `${API_BASE_URL}/api/v1/media-presence/${id}/sync-status`,
    transcript: (id: number) => `${API_BASE_URL}/api/v1/media-presence/${id}/transcript`,
    searchHistory: `${API_BASE_URL}/api/v1/media-presence/search-history`,
  },
};

export const getAuthHeaders = (token?: string) => {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };
  
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }
  
  return headers;
};
